title: "kubernetes the hard way on apple container: Practical Guide"
summary: |
  [kubernetes the hard way](https://github.com/kelseyhightower/kubernetes-the-hard-way) を [apple/container](https://github.com/apple/container) で試した記録です。
topics: ["kubernetes", "applecontainer" ]
published: false
price: 0