mv 00{-,.}prerequisites.md
mv 01{-,.}jumpbox-and-nodes.md
mv 02{-,.}certificate-authority.md
mv 03{-,.}bootstrapping-etcd.md
mv 04{-,.}bootstrapping-controlplane.md
mv 05{-,.}preparing-rbac.md
mv 06{-,.}bootstrapping-crio.md
mv 07{-,.}bootstrapping-workernode.md
mv 08{-,.}enabling-kubernetes-addons.md
mv 09{-,.}verifying-the-cluster.md
mv 10{-,.}cleaning-up.md
mv 13{-,.}appendix.md
